console.log('Begin js');
var select1 = document.getElementById('first');
var select1b = document.getElementsByClassName('special')[0];
var select1c = document.getElementsByTagName('p')[0];
var select2 = document.querySelector('#first');
var select2b = document.querySelector('.special');
var select2b = document.querySelectorAll('.special')[0];
var select3 = document.querySelector('p');
var select3b = document.querySelectorAll('p')[0];
console.log('End js');